name: Demo

on:
  push:
    branches:
      - main
jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.commit.outputs.sha_short }}
      message: ${{ steps.commit.outputs.message }}
      author: ${{ steps.commit.outputs.author }}
      count: ${{ steps.stepid.outputs.count }}
    steps:
      - uses: actions/checkout@v2
      - name: Get SHA short, message, author from commit
        id: commit
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=message::$(git log -1 --pretty=%B)"
          echo "::set-output name=author::$(git log -1 --pretty=%an)"
      - name: Set output
        id: stepid
        run: echo "count=5" >> $GITHUB_OUTPUT
  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Print SHA, message, author from Job 1
        run: |
          echo "SHA: ${{ needs.job-1.outputs.sha_short }}"
          echo "Message: ${{ needs.job-1.outputs.message }}"
          echo "Author: ${{ needs.job-1.outputs.author }}"
      - name: Print count from Job 1
        run: |
          echo "Count: ${{ needs.job-1.outputs.count }}"
