name: Demo

on:
  push:
    branches:
      - main
jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get SHA, message, author from commit
        id: commit
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "::set-output name=message::$(git log -1 --pretty=%B)"
          echo "::set-output name=author::$(git log -1 --pretty=%an)"
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
      message: ${{ steps.commit.outputs.message }}
      author: ${{ steps.commit.outputs.message }}
  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Print SHA, message, author from Job 1
        run: |
          echo "SHA: ${{ needs.job-1.outputs.sha }}"
          echo "Message: ${{ needs.job-1.outputs.message }}"
          echo "Author: ${{ needs.job-1.outputs.author }}"
