name: Docker Image Build

on: workflow_call

jobs:
  linting:
    name: Docker Image Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: docker build -t my-docker-image .