name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/lint.yaml

  unit-testing:
    needs: linting
    name: Unit Testing
    uses: ./.github/workflows/unit-test.yaml