name: Release Workflow

on: 
  push: 
    tags: 
      - 'v[0-9]+.[0-9]+*'

jobs:
  linting:
    name: Docker Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Builds Docker Image
        uses: ./.github/actions/docker-build.yml